# Generated by Django 4.2.29 on 2026-04-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общее расстояние, км')),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Расчётное время, ч')),
                ('estimated_fuel_l', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Расчётный расход топлива, л')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.driver', verbose_name='Водитель')),
                ('orders', models.ManyToManyField(blank=True, related_name='routes', to='orders.order', verbose_name='Заказы')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('loading', 'Погрузка'), ('unloading', 'Разгрузка'), ('intermediate', 'Промежуточная')], default='intermediate', max_length=20, verbose_name='Тип точки')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('sequence', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('scheduled_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Плановое время прибытия')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='orders.order', verbose_name='Заказ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['route', 'sequence'],
            },
        ),
    ]
