# Generated by Django 4.2.29 on 2026-04-05 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='actual_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактическое расстояние, км'),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_fuel_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Фактический расход топлива, л'),
        ),
        migrations.AddField(
            model_name='route',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время отправления'),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_completion_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Расчётное время завершения'),
        ),
        migrations.AddField(
            model_name='route',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания диспетчера'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('in_progress', 'В выполнении'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прибытия'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='Посещена'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterUniqueTogether(
            name='waypoint',
            unique_together={('route', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status', 'is_active'], name='routes_rout_status_a7e3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['vehicle', 'status'], name='routes_rout_vehicle_f70f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['driver', 'status'], name='routes_rout_driver__678836_idx'),
        ),
    ]
