# Generated by Django 4.2.29 on 2026-04-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер путевого листа')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('valid_until', models.DateField(verbose_name='Действителен до')),
                ('route_description', models.TextField(blank=True, verbose_name='Описание маршрута')),
                ('fuel_issued', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Топливо выдано, л')),
                ('fuel_returned', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Топливо сдано, л')),
                ('mileage_start', models.IntegerField(default=0, verbose_name='Пробег при выезде, км')),
                ('mileage_end', models.IntegerField(default=0, verbose_name='Пробег при возвращении, км')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='transport.driver', verbose_name='Водитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='orders.order', verbose_name='Заказ')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='transport.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='WaybillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='waybill_docs/', verbose_name='Файл')),
                ('doc_type', models.CharField(choices=[('ttn', 'ТТН'), ('act', 'Акт'), ('photo', 'Фото'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracking.waybill', verbose_name='Путевой лист')),
            ],
            options={
                'verbose_name': 'Документ путевого листа',
                'verbose_name_plural': 'Документы путевого листа',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('arrived_loading', 'Прибытие на погрузку'), ('loading_start', 'Начало погрузки'), ('loading_end', 'Завершение погрузки'), ('departed', 'Выезд'), ('arrived_unloading', 'Прибытие на разгрузку'), ('unloading_start', 'Начало разгрузки'), ('unloading_end', 'Завершение разгрузки'), ('completed', 'Завершение'), ('delay', 'Задержка'), ('custom', 'Другое')], max_length=30, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие отслеживания',
                'verbose_name_plural': 'События отслеживания',
                'ordering': ['-timestamp'],
            },
        ),
    ]
