# Generated by Django 4.2.29 on 2026-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('cargo_name', models.CharField(max_length=255, verbose_name='Наименование груза')),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес, кг')),
                ('cargo_volume_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём, м³')),
                ('hazard_class', models.IntegerField(default=0, verbose_name='Класс опасности')),
                ('loading_address', models.TextField(verbose_name='Адрес погрузки')),
                ('unloading_address', models.TextField(verbose_name='Адрес разгрузки')),
                ('loading_datetime', models.DateTimeField(verbose_name='Дата/время загрузки')),
                ('required_delivery_datetime', models.DateTimeField(verbose_name='Требуемая дата доставки')),
                ('special_conditions', models.TextField(blank=True, verbose_name='Особые условия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('assigned', 'Назначен на рейс'), ('in_transit', 'В пути'), ('loaded', 'Загружен'), ('unloaded', 'Выгружен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('documents', models.FileField(blank=True, null=True, upload_to='order_docs/', verbose_name='Документы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_attachments/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
            ],
            options={
                'verbose_name': 'Вложение заказа',
                'verbose_name_plural': 'Вложения заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Лог статуса заказа',
                'verbose_name_plural': 'Логи статусов заказов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
