# Generated by Django 4.2.29 on 2026-04-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер удостоверения')),
                ('license_category', models.CharField(default='C', max_length=20, verbose_name='Категория прав')),
                ('medical_exam_date', models.DateField(blank=True, null=True, verbose_name='Дата медосмотра')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('vehicle_type', models.CharField(choices=[('van', 'Фургон'), ('refrigerator', 'Рефрижератор'), ('tank', 'Цистерна'), ('flatbed', 'Бортовой'), ('container', 'Контейнеровоз'), ('other', 'Другое')], default='van', max_length=20, verbose_name='Тип ТС')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Грузоподъёмность, кг')),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Объём кузова, м³')),
                ('current_mileage', models.IntegerField(default=0, verbose_name='Текущий пробег, км')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Расход топлива, л/100км')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата следующего ТО')),
                ('status', models.CharField(choices=[('ok', 'Исправен'), ('repair', 'В ремонте'), ('on_line', 'На линии'), ('write_off', 'Списан')], default='ok', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возвращения')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег за рейс, км')),
                ('fuel_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Расход топлива, л')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='transport.driver', verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to='transport.vehicle', verbose_name='ТС')),
            ],
            options={
                'verbose_name': 'Журнал рейса',
                'verbose_name_plural': 'Журнал рейсов',
                'ordering': ['-departure_date'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.vehicle', verbose_name='Закреплённое ТС'),
        ),
    ]
