# Generated by Django 4.2.29 on 2026-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('hazard_class', models.IntegerField(default=0, help_text='0 — неопасный, 1-9 — классы опасности', verbose_name='Класс опасности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Тип ТС')),
                ('consumption_city', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Расход город, л/100км')),
                ('consumption_highway', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Расход трасса, л/100км')),
                ('consumption_winter', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Зимняя надбавка, л/100км')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
            ],
            options={
                'verbose_name': 'Норматив топлива',
                'verbose_name_plural': 'Нормативы топлива',
            },
        ),
    ]
